"""
report_generator.py
-------------------
Stage 8: AI Report Generation

Uses the Anthropic API to generate a professional Market Entry
Recommendation Report synthesising all analytical outputs:
  - EDA findings
  - Scorecard results
  - Financial model outputs
  - Risk assessment

Output: A structured report in consulting language covering:
  - Executive Summary
  - City Analysis
  - Comparative Scorecard
  - Financial Projections
  - Risk Assessment
  - Final Recommendation
  - Implementation Roadmap

Author: Vinay Wakadkar
Project: Meridian Consumer Goods — Market Entry Analysis
"""

import json
import os
import pandas as pd

# ── Paths ──────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR  = os.path.join(BASE_DIR, 'outputs', 'reports')
os.makedirs(OUT_DIR, exist_ok=True)

def load_analytical_outputs():
    """
    Loads all analytical outputs generated by previous stages.
    These become the structured inputs to the AI report generator.
    """
    # ── Scorecard ──────────────────────────────────────────────
    scorecard_path = os.path.join(OUT_DIR, 'scorecard.json')
    with open(scorecard_path, 'r') as f:
        scorecard = json.load(f)

    # ── Financial model outputs ────────────────────────────────
    projections = pd.read_csv(os.path.join(OUT_DIR, 'revenue_projections.csv'))
    costs       = pd.read_csv(os.path.join(OUT_DIR, 'cost_structure.csv'))
    breakeven   = pd.read_csv(os.path.join(OUT_DIR, 'breakeven_analysis.csv'))
    risk        = pd.read_csv(os.path.join(OUT_DIR, 'risk_register.csv'))

    # ── Summarise financial outputs for API prompt ─────────────
    # Year 1 revenue summary
    yr1_rev = projections[projections['year'] == 1]\
        .groupby(['city', 'scenario'])['monthly_revenue_inr']\
        .sum().reset_index()
    yr1_rev['annual_crore'] = (yr1_rev['monthly_revenue_inr'] / 1e7).round(2)

    # Breakeven summary
    breakeven_summary = {}
    for city in ['Nashik', 'Nagpur', 'Mysuru']:
        city_be = {}
        for scenario in ['Conservative', 'Base', 'Optimistic']:
            city_data = breakeven[
                (breakeven['city'] == city) &
                (breakeven['scenario'] == scenario)
            ]
            profitable = city_data[city_data['cumulative_profit'] >= 0]
            city_be[scenario] = int(profitable['month'].iloc[0]) \
                if len(profitable) > 0 else 'Beyond 36 months'
        breakeven_summary[city] = city_be

    # Year 1 cost summary
    yr1_costs = costs[costs['month'] <= 12]\
        .groupby('city')['total_monthly_cost'].sum().reset_index()
    yr1_costs['annual_crore'] = (yr1_costs['total_monthly_cost'] / 1e7).round(2)

    return {
        'scorecard': scorecard,
        'yr1_revenue': yr1_rev.to_dict(orient='records'),
        'breakeven_summary': breakeven_summary,
        'yr1_costs': yr1_costs.to_dict(orient='records'),
        'risk_register': risk[['risk_id', 'risk', 'risk_score',
                               'risk_level', 'mitigation']].to_dict(orient='records'),
    }

def generate_report(analytical_outputs):
    """
    Passes structured analytical outputs to Groq API.
    Generates a professional Market Entry Recommendation Report.
    """
    from groq import Groq

    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""
You are a senior consultant at a Big Four consulting firm. 
You have just completed a market entry analysis for Meridian Consumer Goods Pvt. Ltd., 
a mid-market FMCG company based in Pune, Maharashtra.

The client is deciding which of three Tier 2 cities to enter next:
Nashik, Nagpur, or Mysuru. They have a budget of ₹8-12 crore for Year 1.

Here are the complete analytical outputs from your engagement:

## SCORECARD RESULTS (Weighted scores out of 1.0)
{json.dumps(analytical_outputs['scorecard'], indent=2)}

## YEAR 1 REVENUE PROJECTIONS (₹ crore)
{json.dumps(analytical_outputs['yr1_revenue'], indent=2)}

## BREAKEVEN ANALYSIS (Month number)
{json.dumps(analytical_outputs['breakeven_summary'], indent=2)}

## YEAR 1 COST STRUCTURE (₹ crore)
{json.dumps(analytical_outputs['yr1_costs'], indent=2)}

## RISK REGISTER
{json.dumps(analytical_outputs['risk_register'], indent=2)}

Based on these outputs, write a professional Market Entry Recommendation Report 
with the following sections:

1. EXECUTIVE SUMMARY (3-4 sentences — the recommendation and key rationale)

2. CITY ANALYSIS (2-3 paragraphs per city — market potential, competitive position, 
   operational feasibility, financial outlook)

3. COMPARATIVE SCORECARD SUMMARY (narrative interpretation of the scorecard results)

4. FINANCIAL PROJECTIONS SUMMARY (narrative covering TAM, Year 1-3 revenue outlook, 
   breakeven timelines across scenarios)

5. RISK ASSESSMENT SUMMARY (top 3 risks and their mitigations in narrative form)

6. FINAL RECOMMENDATION (clear, specific, defensible — which city, why, 
   with conditions and assumptions stated)

7. IMPLEMENTATION ROADMAP (phased entry plan — pre-launch, Month 1-3, Month 4-6, 
   Month 7-12, Year 2 priorities)

Write in professional consulting language. Be specific — cite actual numbers 
from the analytical outputs. Be direct — do not hedge excessively. 
The client is a Board that needs a clear recommendation, not a list of options.

Do not use markdown formatting. Write in clean prose with numbered section headers.
"""

    print("Generating report via Groq API...")
    print("This may take 30-60 seconds...\n")

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        max_tokens=4000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    report_text = response.choices[0].message.content
    return report_text

def save_report(report_text):
    """
    Saves the generated report as a text file.
    """
    report_path = os.path.join(OUT_DIR, 'market_entry_recommendation.txt')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("MERIDIAN CONSUMER GOODS PVT. LTD.\n")
        f.write("MARKET ENTRY RECOMMENDATION REPORT\n")
        f.write("Prepared by: Vinay Wakadkar\n")
        f.write("=" * 60 + "\n\n")
        f.write(report_text)

    print(f"Report saved to: {report_path}")
    return report_path

if __name__ == '__main__':
    print("=" * 60)
    print("MERIDIAN MARKET ENTRY — REPORT GENERATION")
    print("=" * 60)

    # Load all analytical outputs
    outputs = load_analytical_outputs()

    # Generate report
    report = generate_report(outputs)

    # Print report
    print("\n" + "=" * 60)
    print("GENERATED REPORT")
    print("=" * 60)
    print(report)

    # Save report
    save_report(report)
    print("\nReport generation complete.")

